import {
  AppstoreOutlined,
  ContainerOutlined,
  DesktopOutlined,
  PieChartOutlined,
} from '@ant-design/icons'

export const LeftPannalrData = [
  {
    title: 'Dashboard',
    link: '/',
    preIcion: PieChartOutlined,
    postIcion: '<URL>',
    active: true,
    subMenu: [
      {
        title: 'Profile',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Profile',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'User Management',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
  {
    title: 'Restaurant Management',
    link: '/',
    preIcion: DesktopOutlined,
    postIcion: '▶️',
    active: true,
    subMenu: [
      {
        title: 'Payment',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Bill',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Reports',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'People',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
  {
    title: 'User Management',
    link: '/',
    preIcion: AppstoreOutlined,
    postIcion: '<URL>',
    active: true,
    subMenu: [
      {
        title: 'Voucher',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Voucher',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Adminstrative Tools',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Offer',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
  {
    title: 'Company',
    link: '/',
    preIcion: ContainerOutlined,
    postIcion: '<URL>',
    active: true,
    subMenu: [
      {
        title: 'Offer',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Offer',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Offer',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
]
