version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3000" # Maps container port 3000 to host port 3000
    environment:
      - NODE_ENV=production # Ensures the app runs in production mode
