import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { User } from '../types/userTypes'

// Initial state
import initialState from '../constants/initialState'

// Create a slice using createSlice
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    fetchUsersSuccess: (state, action: PayloadAction<User[]>) => {
      state.users = [...state.users, ...action.payload]
    },
    fetchUsersError: (state, action: PayloadAction<string>) => {
      state.error = action.payload
    },
    setPage: (state, action: PayloadAction<number>) => {
      state.page = action.payload
    },
  },
})

// Export actions generated by createSlice
export const { fetchUsersSuccess, fetchUsersError, setPage } = userSlice.actions

// Export the reducer to be used in the store
export default userSlice.reducer
