export const HeaderData = [
  {
    title: 'Home',
    link: '/',
    preIcion: '<URL>',
    postIcion: '<URL>',
    active: true,
    subMenu: [
      {
        title: 'Home',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
  {
    title: 'Menu',
    link: '/',
    preIcion: '🔽',
    postIcion: '▶️',
    active: true,
    subMenu: [
      {
        title: 'Home1',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home2',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home3',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
      {
        title: 'Home4',
        link: '/',
        preIcion: '<URL>',
        postIcion: '<URL>',
        active: true,
      },
    ],
  },
  {
    title: 'Contact',
    link: '/',
    preIcion: '<URL>',
    postIcion: '<URL>',
    active: true,
    subMenu: [],
  },
  {
    title: 'Order Now',
    link: '/',
    preIcion: '<URL>',
    postIcion: '<URL>',
    active: true,
    subMenu: [],
  },
]
